AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for SIF Deployment
Resources:
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'sif-deploy-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  SifDeployPolicyOne:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - Ref: CloudFormationExecutionRole
      ManagedPolicyName: SifDeployPolicyOne
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - apigateway:CreateAuthorizer
              - apigateway:CreateDeployment
              - apigateway:CreateResource
              - apigateway:CreateRestApi
              - apigateway:CreateStage
              - apigateway:DeleteAuthorizer
              - apigateway:DeleteDeployment
              - apigateway:DeleteMethod
              - apigateway:DeleteResource
              - apigateway:DeleteRestApi
              - apigateway:DeleteStage
              - apigateway:GetDeployment
              - apigateway:GetResources
              - apigateway:GetRestApi
              - apigateway:GetStage
              - apigateway:PutIntegration
              - apigateway:PutIntegrationResponse
              - apigateway:PutMethod
              - apigateway:PutMethodResponse
              - apigateway:TagResource
              - apigateway:UntagResource
              - apigateway:UpdateAccount
              - apigateway:UpdateDeployment
              - apigateway:UpdateRestApi
              - apigateway:UpdateStage
              - apigateway:GET
              - apigateway:PUT
              - apigateway:POST
              - apigateway:DELETE
              - apigateway:PATCH
            Resource: "*"
          - Effect: Allow
            Action:
              - events:CreateEventBus
              - events:DeleteEventBus
              - events:DeleteRule
              - events:RemoveTargets
              - events:DescribeRule
              - events:DescribeEventBus
              - events:TagResource
              - events:ListTagsForResource
              - events:UntagResource
              - events:PutTargets
              - events:PutRule
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:UpdateTerminationProtection
              - cloudformation:CreateChangeSet
              - cloudformation:GetTemplateSummary
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:CreateStack
              - cloudformation:GetTemplate
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - sts:GetCallerIdentity
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:CreateUserPool
              - ec2:AllocateAddress
              - ec2:CreateTags
              - ec2:DeleteTags
              - ec2:DescribeAccountAttributes
              - ec2:DescribeAddresses
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeClientVpnEndpoints
              - ec2:DescribeFlowLogs
              - ec2:DescribeInternetGateways
              - ec2:DescribeNatGateways
              - ec2:DescribeNetworkAcls
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcEndpoints
              - ec2:DescribeVpcs
              - ec2:DisassociateRouteTable
              - ec2:ReleaseAddress
              - ecs:CreateCluster
              - ecs:DeregisterTaskDefinition
              - ecs:ListTagsForResource
              - ecs:RegisterTaskDefinition
              - ecs:TagResource
              - ecs:UntagResource
              - kms:CreateKey
              - lambda:CreateEventSourceMapping
              - lambda:DeleteProvisionedConcurrencyConfig
              - lambda:GetProvisionedConcurrencyConfig
              - lambda:PutProvisionedConcurrencyConfig
              - lambda:UpdateEventSourceMapping
              - logs:DescribeLogGroups
              - rds:AddTagsToResource
              - rds:CreateDBProxy
              - rds:DescribeEvents
              - rds:ListTagsForResource
              - rds:RemoveTagsFromResource
              - route53:AssociateVPCWithHostedZone
              - secretsmanager:GetRandomPassword
              - ssm:AddTagsToResource
              - ssm:RemoveTagsFromResource
            Resource: "*"


  SifDeployPolicyTwo:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - Ref: CloudFormationExecutionRole
      ManagedPolicyName: SifDeployPolicyTwo
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
            Resource: "*"
          - Effect: Allow
            Action:
              - cognito-idp:AdminAddUserToGroup
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminDeleteUser
              - cognito-idp:AdminRemoveUserFromGroup
              - cognito-idp:CreateGroup
              - cognito-idp:CreateUserPoolClient
              - cognito-idp:CreateUserPoolDomain
              - cognito-idp:UpdateUserPool
              - cognito-idp:DeleteGroup
              - cognito-idp:DeleteUserPool
              - cognito-idp:DeleteUserPoolClient
              - cognito-idp:DeleteUserPoolDomain
              - cognito-idp:TagResource
              - cognito-idp:UntagResource
              - cognito-idp:ListTagsForResource
            Resource: "*"
          - Effect: Allow
            Action:
              - dynamodb:CreateTable
              - dynamodb:DeleteTable
              - dynamodb:DescribeContinuousBackups
              - dynamodb:DescribeContributorInsights
              - dynamodb:DescribeKinesisStreamingDestination
              - dynamodb:DescribeTable
              - dynamodb:DescribeTimeToLive
              - dynamodb:ListTagsOfResource
              - dynamodb:TagResource
              - dynamodb:UntagResource
              - dynamodb:UpdateContinuousBackups
              - dynamodb:UpdateTimeToLive
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:AuthorizeClientVpnIngress
              - ec2:CreateClientVpnEndpoint
              - ec2:DeleteClientVpnEndpoint
              - ec2:DeleteClientVpnRoute
              - ec2:DescribeClientVpnAuthorizationRules
              - ec2:DescribeClientVpnRoutes
              - ec2:DescribeClientVpnTargetNetworks
              - ec2:DisassociateClientVpnTargetNetwork
              - ec2:RevokeClientVpnIngress
            Resource: "*"
          - Effect: Allow
            Action: ec2:AllocateAddress
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:CreateInternetGateway
              - ec2:DeleteInternetGateway
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:DeleteNatGateway
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:AssociateRouteTable
              - ec2:CreateRoute
              - ec2:DeleteRoute
              - ec2:DeleteRouteTable
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:AssociateClientVpnTargetNetwork
              - ec2:CreateClientVpnRoute
              - ec2:CreateNatGateway
              - ec2:DeleteSubnet
              - ec2:ModifySubnetAttribute
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:CreateFlowLogs
              - ec2:DeleteFlowLogs
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:AttachInternetGateway
              - ec2:CreateRouteTable
              - ec2:CreateSubnet
              - ec2:CreateVpc
              - ec2:CreateVpcEndpoint
              - ec2:ModifyVpcEndpoint
              - ec2:DeleteVpc
              - ec2:DeleteVpcEndpoints
              - ec2:DescribeVpcAttribute
              - ec2:DetachInternetGateway
              - ec2:ModifyVpcAttribute
            Resource: "*"
          - Effect: Allow
            Action:
              - ecs:DeleteCluster
              - ecs:DescribeClusters
              - ecs:PutClusterCapacityProviders
            Resource: "*"
          - Effect: Allow
            Action:
              - firehose:CreateDeliveryStream
              - firehose:DeleteDeliveryStream
              - firehose:DescribeDeliveryStream
              - firehose:TagDeliveryStream
              - firehose:UntagDeliveryStream
              - firehose:UpdateDestination
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:AttachRolePolicy
              - iam:CreateRole
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
              - iam:DeleteRole
              - iam:DeleteRolePolicy
              - iam:DetachRolePolicy
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:PassRole
              - iam:PutRolePolicy
              - iam:TagRole
              - iam:UntagRole
            Resource: "*"
          - Effect: Allow
            Action:
              - kinesis:AddTagsToStream
              - kinesis:CreateStream
              - kinesis:DeleteStream
              - kinesis:DescribeStreamSummary
              - kinesis:ListTagsForStream
              - kinesis:RemoveTagsFromStream
              - kinesis:StartStreamEncryption
            Resource: "*"
          - Effect: Allow
            Action:
              - kms:CreateGrant
              - kms:Decrypt
              - kms:DescribeKey
              - kms:EnableKeyRotation
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GetKeyPolicy
              - kms:GetKeyRotationStatus
              - kms:ListResourceTags
              - kms:PutKeyPolicy
              - kms:TagResource
              - kms:UntagResource
            Resource: "*"
          - Effect: Allow
            Action:
              - lambda:DeleteEventSourceMapping
              - lambda:GetEventSourceMapping
            Resource: "*"
          - Effect: Allow
            Action:
              - lambda:AddPermission
              - lambda:CreateAlias
              - lambda:CreateFunction
              - lambda:UpdateAlias
              - lambda:DeleteAlias
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:GetFunctionCodeSigningConfig
              - lambda:GetRuntimeManagementConfig
              - lambda:ListTags
              - lambda:ListVersionsByFunction
              - lambda:PublishVersion
              - lambda:RemovePermission
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:UpdateFunctionCode
              - lambda:InvokeFunction
              - lambda:UpdateFunctionConfiguration
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogDelivery
              - logs:CreateLogStream
              - logs:DeleteLogGroup
              - logs:ListTagsLogGroup
              - logs:PutRetentionPolicy
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - logs:DeleteLogDelivery
            Resource: "*"

  SifDeployPolicyThree:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - Ref: CloudFormationExecutionRole
      ManagedPolicyName: SifDeployPolicyThree
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - rds:CreateDBCluster
              - rds:DeleteDBCluster
              - rds:DescribeDBClusters
              - rds:AddRoleToDBCluster
              - rds:RemoveRoleFromDBCluster
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:CreateDBProxyEndpoint
              - rds:DeleteDBProxyEndpoint
              - rds:ModifyDBProxyEndpoint
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:DeleteDBProxy
              - rds:DescribeDBProxies
              - rds:DescribeDBProxyEndpoints
              - rds:ModifyDBProxy
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:CreateDBInstance
              - rds:DeleteDBInstance
              - rds:DescribeDBInstances
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:ModifyDBCluster
              - rds:ModifyDBInstance
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:CreateDBParameterGroup
              - rds:DeleteDBParameterGroup
              - rds:DescribeDBParameterGroups
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:CreateDBSubnetGroup
              - rds:DeleteDBSubnetGroup
              - rds:DescribeDBSubnetGroups
              - rds:ModifyDBSubnetGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:DeregisterDBProxyTargets
              - rds:DescribeDBProxyTargets
              - rds:ModifyDBProxyTargetGroup
              - rds:RegisterDBProxyTargets
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:DeleteBucketPolicy
              - s3:GetBucketPolicy
              - s3:PutBucketCORS
              - s3:PutBucketLogging
              - s3:PutBucketPolicy
              - s3:PutBucketPublicAccessBlock
              - s3:PutBucketTagging
              - s3:PutBucketVersioning
              - s3:PutEncryptionConfiguration
              - s3:PutIntelligentTieringConfiguration
            Resource: "*"
          - Effect: Allow
            Action:
              - secretsmanager:CancelRotateSecret
              - secretsmanager:CreateSecret
              - secretsmanager:DeleteResourcePolicy
              - secretsmanager:DeleteSecret
              - secretsmanager:DescribeSecret
              - secretsmanager:GetResourcePolicy
              - secretsmanager:GetSecretValue
              - secretsmanager:PutResourcePolicy
              - secretsmanager:RotateSecret
              - secretsmanager:TagResource
              - secretsmanager:UntagResource
              - secretsmanager:UpdateSecret
            Resource: "*"
          - Effect: Allow
            Action:
              - sagemaker:DeleteModel
              - sagemaker:DescribeModel
              - sagemaker:DeleteEndpointConfig
              - sagemaker:DescribeEndpointConfig
              - sagemaker:DescribeEndpoint
              - sagemaker:DeleteEndpoint
              - sagemaker:UpdateEndpoint
              - sagemaker:AddTags
              - sagemaker:CreateEndpointConfig
              - sagemaker:CreateModel
              - sagemaker:CreateEndpoint
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:CreateQueue
              - sqs:DeleteQueue
              - sqs:SetQueueAttributes
              - sqs:GetQueueAttributes
              - sqs:TagQueue
              - sqs:UntagQueue
            Resource: "*"
          - Effect: Allow
            Action:
              - ssm:DeleteParameter
              - ssm:GetParameters
              - ssm:PutParameter
            Resource: "*"
          - Effect: Allow
            Action:
              - glue:CreateDatabase
              - glue:CreateTable
              - glue:DeleteDatabase
              - glue:DeleteTable
            Resource: "*"
          - Effect: Allow
            Action:
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:DescribeScalableTargets
              - application-autoscaling:DescribeScalingPolicies
              - application-autoscaling:DescribeScheduledActions
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget
            Resource: "*"
          - Effect: Allow
            Action:
              - states:CreateStateMachine
              - states:DeleteStateMachine
              - states:DescribeStateMachine
              - states:TagResource
              - states:UntagResource
              - states:UpdateStateMachine
            Resource: "*"
