/*
 *  Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

import { Stack, StackProps } from 'aws-cdk-lib';
import { PipelinesModule } from './pipelines.construct.js';
import type { Construct } from 'constructs';
import { StringParameter } from 'aws-cdk-lib/aws-ssm';
import { ResourceApiBase } from '../shared/resourceApiBase.construct.js';
import { userPoolIdParameter } from '../shared/cognito.construct.js';
import { eventBusNameParameter } from '../shared/eventbus.construct.js';
import { NagSuppressions } from 'cdk-nag';
import { accessManagementApiFunctionNameParameter, calculatorFunctionNameParameter, pipelinesApiFunctionNameParameter } from '../shared/ssm.construct.js';

export type PipelineStackProperties = StackProps & {
	tenantId: string;
	environment: string;
	enableDeleteResource?: boolean;
};

export class PipelineApiStack extends Stack {
	constructor(scope: Construct, id: string, props?: PipelineStackProperties) {
		super(scope, id, props);

		// validation
		this.validateMandatoryParam(props, 'tenantId');
		this.validateMandatoryParam(props, 'environment');

		const cognitoUserPoolId = StringParameter.fromStringParameterAttributes(this, 'userPoolId', {
			parameterName: userPoolIdParameter(props.tenantId, props.environment),
			simpleName: false,
		}).stringValue;

		const eventBusName = StringParameter.fromStringParameterAttributes(this, 'eventBusName', {
			parameterName: eventBusNameParameter(props.tenantId, props.environment),
			simpleName: false,
		}).stringValue;

		const accessManagementApiFunctionName = StringParameter.fromStringParameterAttributes(this, 'accessManagementApiFunctionName', {
			parameterName: accessManagementApiFunctionNameParameter(props.tenantId, props.environment),
			simpleName: false,
		}).stringValue;

		const pipelinesApiFunctionName = StringParameter.fromStringParameterAttributes(this, 'pipelineApiFunctionName', {
			parameterName: pipelinesApiFunctionNameParameter(props.tenantId, props.environment),
			simpleName: false,
		}).stringValue;

		const calculatorFunctionName = StringParameter.fromStringParameterAttributes(this, 'calculatorFunctionName', {
			parameterName: calculatorFunctionNameParameter(props.tenantId, props.environment),
			simpleName: false,
		}).stringValue;


		const base = new ResourceApiBase(this, 'ResourceApiBase', {
			tenantId: props.tenantId,
			environment: props.environment,
			moduleName: 'pipelines',
			eventBusName,
			auth: {
				accessManagementApiFunctionName,
			},
			queue: {
				moduleSqsLambdaLocation: '../../../../typescript/packages/apps/pipelines/src/lambda_sqs.ts',
				pnpmLockFileLocation: '../../../../common/config/rush/pnpm-lock.yaml',
			},
		});

		const module = new PipelinesModule(this, 'Pipelines', {
			tenantId: props.tenantId,
			environment: props.environment,
			accessManagementApiFunctionName,
			cognitoUserPoolId,
			eventBusName,
			tableName: base.tableName,
			workerQueueArn: base.workerQueueArn,
			enableDeleteResource: props.enableDeleteResource,
			calculatorFunctionName: calculatorFunctionName,
			pipelinesApiFunctionName,
		});
		module.node.addDependency(base);

		NagSuppressions.addResourceSuppressionsByPath(this, [
				'/Pipelines/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/Resource'
			],
			[
				{
					id: 'AwsSolutions-IAM4',
					appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
					reason: 'This policy attached to the role is generated by CDK.'

				},
				{
					id: 'AwsSolutions-IAM5',
					appliesTo: ['Resource::*'],
					reason: 'The resource condition in the IAM policy is generated by CDK, this only applies to logs:DeleteRetentionPolicy and logs:PutRetentionPolicy actions.'

				}],
			true);
	}

	private validateMandatoryParam(props: PipelineStackProperties, name: string) {
		if (props[name] === undefined) {
			throw new Error(`${name} is required`);
		}
	}
}
